hardcandyresinarts/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('shop/', include('shop.urls')),
    path('about/', include('about.urls')),
    path('basket/', include('basket.urls')),
    path('checkout/', include('checkout.urls')),
    path('profile/', include('profiles.urls')),
    path('newsletter/', include('newsletter.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='home')
]

shop/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.shop_products, name='shop_products'),
    path('<product_id>', views.product_detail, name='product_detail'),
]

checkout/models.py
import uuid

from django.db import models
from django.db.models import Sum
from django.conf import settings

from django_countries.fields import CountryField

from shop.models import Product
from profiles.models import UserProfile

# Create your models here.

class Order(models.Model):
    order_number = models.CharField(max_length=32, null=False, editable=False)
    user_profile = models.ForeignKey(UserProfile, on_delete=models.SET_NULL,
                                     null=True, blank=True, related_name='orders')
    full_name = models.CharField(max_length=50, null=False, blank=False)
    email = models.EmailField(max_length=254, null=False, blank=False)
    phone_number = models.CharField(max_length=20, null=False, blank=False)
    country = CountryField(blank_label='Country *', null=False, blank=False)
    postcode = models.CharField(max_length=20, null=True, blank=True)
    town_or_city = models.CharField(max_length=40, null=False, blank=False)
    street_address1 = models.CharField(max_length=80, null=False, blank=False)
    street_address2 = models.CharField(max_length=80, null=True, blank=True)
    county = models.CharField(max_length=80, null=True, blank=True)
    date = models.DateTimeField(auto_now_add=True)
    delivery_cost = models.DecimalField(max_digits=6, decimal_places=2, null=False, default=0)
    order_total = models.DecimalField(max_digits=10, decimal_places=2, null=False, default=0)
    grand_total = models.DecimalField(max_digits=10, decimal_places=2, null=False, default=0)
    original_basket = models.TextField(null=False, blank=False, default='')
    stripe_pid = models.CharField(max_length=254, null=False, blank=False, default='')

    def _generate_order_number(self):
        """
        Generate a random, unique order number using UUID
        """
        return uuid.uuid4().hex.upper()

    def update_total(self):
        """
        Update grand total each time a line item is added,
        accounting for delivery costs.
        """
        self.order_total = self.lineitems.aggregate(Sum('lineitem_total'))['lineitem_total__sum'] or 0
        if self.order_total < settings.FREE_DELIVERY_THRESHOLD:
            self.delivery_cost = self.order_total * settings.STANDARD_DELIVERY_PERCENTAGE / 100
        else:
            self.delivery_cost = 0
        self.grand_total = self.order_total + self.delivery_cost
        self.save()

    def save(self, *args, **kwargs):
        """
        Override the original save method to set the order number
        if it hasn't been set already.
        """
        if not self.order_number:
            self.order_number = self._generate_order_number()
        super().save(*args, **kwargs)

    def __str__(self):
        return self.order_number

class OrderLineItem(models.Model):
    order = models.ForeignKey(Order, null=False, blank=False, on_delete=models.CASCADE, related_name='lineitems')
    product = models.ForeignKey(Product, null=False, blank=False, on_delete=models.CASCADE)
    product_size = models.CharField(max_length=2, null=True, blank=True) # XS, S, M, L, XL
    quantity = models.IntegerField(null=False, blank=False, default=0)
    lineitem_total = models.DecimalField(max_digits=6, decimal_places=2, null=False, blank=False, editable=False)

    def save(self, *args, **kwargs):
        """
        Override the original save method to set the lineitem total
        and update the order total.
        """
        self.lineitem_total = self.product.price * self.quantity
        super().save(*args, **kwargs)

    def __str__(self):
        return f'SKU {self.product.sku} on order {self.order.order_number}'

shop/models.py
from django.db import models


class Category(models.Model):

    class Meta:
        verbose_name_plural = 'Categories'

    name = models.CharField(max_length=254)
    friendly_name = models.CharField(max_length=254, null=True, blank=True)

    def __str__(self):
        return self.name

    def get_friendly_name(self):
        return self.friendly_name


class Product(models.Model):
    category = models.ForeignKey('Category', null=True, blank=True, on_delete=models.SET_NULL)
    sku = models.CharField(max_length=254, null=True, blank=True)
    name = models.CharField(max_length=254)
    description = models.TextField()
    # short_desc = models.TextField()
    has_sizes = models.BooleanField(default=False, null=True, blank=True)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    image_url = models.URLField(max_length=1024, null=True, blank=True)
    image = models.ImageField(null=True, blank=True)

    def __str__(self):
        return self.name

shop/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.contrib import messages
from django.db.models import Q
from django.db.models.functions import Lower

from .models import Product, Category


def shop_products(request):
    """ A view to return the shop page """

    products = Product.objects.all()
    query = None
    categories = None
    sort = None
    direction = None

    if request.GET:
        if 'sort' in request.GET:
            sortkey = request.GET['sort']
            sort = sortkey
            if sortkey == 'name':
                sortkey = 'lower_name'
                products = products.annotate(lower_name=Lower('name'))
            if sortkey == 'category':
                sortkey = 'category__name'
            if 'direction' in request.GET:
                direction = request.GET['direction']
                if direction == 'desc':
                    sortkey = f'-{sortkey}'
            products = products.order_by(sortkey)

        if 'category' in request.GET:
            categories = request.GET['category'].split(',')
            products = products.filter(category__name__in=categories)
            categories = Category.objects.filter(name__in=categories)

        if 'q' in request.GET:
            query = request.GET['q']
            if not query:
                messages.error(request,
                               ("You didn't enter any search criteria!"))
                return redirect(reverse('shop_products'))

            queries = Q(name__icontains=query) | Q(description__icontains=query)
            products = products.filter(queries)

    current_sorting = f'{sort}_{direction}'

    context = {
        'products': products,
        'search_term': query,
        'current_categories': categories,
        'current_sorting': current_sorting,
    }

    return render(request, 'shop/shop.html', context)


def product_detail(request, product_id):
    """ A view to return the shop page """

    product = get_object_or_404(Product, pk=product_id)

    context = {
        'product': product,
    }

    return render(request, 'shop/product_detail.html', context)

shop/templates/shop/product_detail.html
{% extends "base.html" %}
{% load static %}

{% block extra_title %}- Shop{% endblock %}

{% block shop %}active{% endblock %}

{% block extra_css %}
    <link rel="stylesheet" href="{% static 'shop/css/shop.css' %}">
{% endblock %}

{% block page_header %}
    <div class="container header-container">
        <div class="row">
            <div class="col"></div>
        </div>
    </div>
{% endblock %}

{% block content %}
<div id="item-details-container" class="container-fluid border-custom">
    <div class="row">
        <div class="col-12 col-lg-4 offset-lg-1">
            <div class="image-container my-5 mb-5 mt-md-5">
                {% if product.image %}
                    <a href="{{ product.image.url }}" target="_blank" rel="noreferrer">
                        <img id="item-image-info" class="card-img-top img-fluid" src="{{ product.image.url }}" alt="{{ product.name }}">
                    </a>
                    {% else %}
                    <a href="">
                        <img class="card-img-top img-fluid" src="{{ MEDIA_URL }}noimage.png" alt="{{ product.name }}">
                    </a>
                {% endif %}
            </div>
        </div>
        <div class="col-12 col-lg-7">
            <div class="product-details-container mb-5 mt-md-5">
                <p id="product-name" class="mb-0">{{ product.name }}</p>
                <p id="price" class="lead mb-0 font-weight-bold">£{{ product.price }}</p>
                {% if product.category %}
                <p class="small mt-1 mb-0">
                    <a id="category" class="text-muted" href="{% url 'shop_products' %}?category={{ product.category.name }}">
                        <i class="fas fa-tag mr-1"></i>{{ product.category.friendly_name }}
                    </a>
                </p>
                {% endif %}
                <p id="product-desc" class="mt-3">{{ product.description }}</p>
                <form class="form" action="{% url 'add_to_basket' product.id %}" method="POST">
                    {% csrf_token %}
                    <div class="form-row">
                        {% with product.has_sizes as s %}
                        {% if s %}
                            <div class="col-12">
                                <p><strong>Size:</strong></p>
                                <select class="form-control rounded-0 w-50" name="product_size" id='id_product_size'>
                                    <option value="xs">XS</option>
                                    <option value="s">S</option>
                                    <option value="m" selected>M</option>
                                    <option value="l">L</option>
                                    <option value="xl">XL</option>
                                </select>
                            </div>
                        {% endif %}
                        <div class="col-12 text-center text-lg-left">
                            <p id="quantity" class="mt-3"><strong>Quantity:</strong></p>
                            <div class="form-group w-50 m-auto m-lg-0 mb-2">
                                <div class="input-group">
                                    <div class="input-group-prepend">
                                        <button class="decrement-qty btn btn-black rounded-0" 
                                            data-item_id="{{ product.id }}" id="decrement-qty_{{ product.id }}">
                                            <span class="icon">
                                                <i class="fas fa-minus"></i>
                                            </span>
                                        </button>
                                    </div>
                                    <input class="form-control qty_input text-center barlow-semi font-weight-bolder" type="number"
                                        name="quantity" value="1" min="1" max="99"
                                        data-item_id="{{ product.id }}"
                                        id="id_qty_{{ product.id }}">
                                    <div class="input-group-append">
                                        <button class="increment-qty btn btn-black rounded-0"
                                            data-item_id="{{ product.id }}" id="increment-qty_{{ product.id }}">
                                            <span class="icon">
                                                <i class="fas fa-plus"></i>
                                            </span>
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <input type="hidden" name="redirect_url" value="{{ request.path }}">
                        {% endwith %}
                    </div>
                    <div class="row">
                        <div class="col-12{% if s %} mt-2{% endif %} text-center text-lg-left">
                            <input id="add-basket" type="submit" class="btn rounded-0 text-uppercase mt-5" value="Add to Basket">
                            <a href="{% url 'shop_products' %}" class="btn btn-outline-black rounded-0 mt-5">
                                <span class="icon">
                                    <i id="back-arrow-menu" class="fas fa-chevron-left"></i>
                                </span>
                                <span id="back-menu" class="text-uppercase">Keep Shopping</span>
                            </a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %} 

{% block postloadjs %}
    {{ block.super }}
    {% include 'shop/includes/quantity_input_script.html' %}
{% endblock %}